# Generated by Django 2.1.5 on 2022-03-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionDateTime', models.DateTimeField()),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('method', models.TextField(max_length=500)),
                ('cookTime', models.CharField(max_length=20)),
                ('Servings', models.CharField(max_length=20)),
                ('Difficutly', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeSite.Recipe'),
        ),
    ]
