# Generated by Django 2.1.5 on 2022-03-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeSite', '0002_auto_20220306_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Difficutly',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Servings',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy to Make'), ('MEDIUM', 'Moderately Difficult'), ('HARD', 'Hard to Make')], default='EASY', max_length=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipeImages'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cookTime',
            field=models.DurationField(),
        ),
    ]
